### ISSUE TITLE
Having trouble with split.c

### ISSUE THREAD

**Issue by braves23** [semitrivial/csv_parser#2]
The documentation says it returns an array of strings so I don't understand why this is not working. Can you please tell me what I did wrong? 

https://ideone.com/RylYp1

**Comment by semitrivial** [comment]
Hi braves23.  `split_on_unescaped_newlines` doesn't mutate its argument, rather, it returns results.  Try this:
```
    char **result = split_on_unescaped_newlines(line);
    printf("line  %s\n", result[0]);
    printf("line  %s\n", result[1]);
```
